export const doctorCouncils = [
    "Medical Council of India",
    "Delhi Medical Council",
    "Maharashtra Medical Council",
    "Tamil Nadu Medical Council",
    "Andhra Pradesh Medical Council",
    "Karnataka Medical Council",
    "West Bengal Medical Council",
    "Punjab Medical Council",
    "Kerala Medical Council",
    "Uttar Pradesh Medical Council",
    "Gujarat Medical Council",
    "Madhya Pradesh Medical Council",
    "Haryana Medical Council",
    "Rajasthan Medical Council",
    "Bihar Medical Council",
    "Chhattisgarh Medical Council",
    "Goa Medical Council",
    "Odisha Medical Council",
    "Assam Medical Council",
    "Telangana State Medical Council",
    "Jammu & Kashmir Medical Council",
    "Jharkhand Medical Council",
    "Himachal Pradesh Medical Council",
    "Sikkim Medical Council",
    "Tripura Medical Council",
    "Manipur Medical Council",
    "Nagaland Medical Council",
    "Arunachal Pradesh Medical Council",
    "Mizoram Medical Council",
    "Pondicherry Medical Council",
    "Chandigarh Medical Council",
    "Uttarakhand Medical Council",
  ];
  