export const  doctorColleges = [
    "All India Institute of Medical Sciences (AIIMS), Delhi",
    "Postgraduate Institute of Medical Education and Research (PGIMER), Chandigarh",
    "Jawaharlal Institute of Postgraduate Medical Education and Research (JIPMER), Puducherry",
    "King George's Medical University (KGMU), Lucknow",
    "Maulana Azad Medical College (MAMC), Delhi",
    "Bangalore Medical College and Research Institute (BMCRI), Bangalore",
    "Lady Hardinge Medical College, Delhi",
    "Amrita Institute of Medical Sciences, Kochi",
    "Seth GS Medical College, Mumbai",
    "Manipal University, Manipal",
    "Institute of Medical Sciences, Banaras Hindu University (BHU), Varanasi",
    "Nizam's Institute of Medical Sciences (NIMS), Hyderabad",
    "Kasturba Medical College, Mangalore",
    "Sri Ramachandra Institute of Higher Education and Research, Chennai",
    "Medical College, Kolkata",
    "Government Medical College, Thiruvananthapuram",
    "Government Medical College, Surat",
    "Government Medical College, Nagpur",
    "Government Medical College, Jammu",
    "Government Medical College, Amritsar",
  ];
  